package com.isssr.ticketing_system.acl;

public enum AuthorityName {
    ROLE_ADMIN,
    ROLE_EDITOR,
    ROLE_CUSTOMER,
    ROLE_TEAM_COORDINATOR,
    ROLE_TEAM_LEADER,
    ROLE_TEAM_MEMBER,
    ROLE_SOFTWARE_PRODUCT_READER,
    ROLE_TEAM_READER,
    ROLE_GROUP_COORDINATOR,
    ROLE_GROUP_READER,
    ROLE_SOFTWARE_PRODUCT_COORDINATOR,
    ROLE_SCRUM
}
